site_name: CallTelemetry
site_url: https://docs.calltelemetry.com
nav:
    - Change Log: changelog.md
    - Licensing: licensing.md
    - Cloud Demo: cloud.md
    - Installation Guide:
      - Architecture: architecture.md
      - Platform:
        - "Platform Choices": deployment/choices.md
        - "OVA Appliance": deployment/ova.md
        - "Kubernetes": deployment/k3s.md
        - "Sizing": deployment/sizing.md
        - "Load Testing": deployment/load-testing.md
      - Integration to Callmanager:
        - "Call Control": setup/curri.md
        - "CDR": setup/cdr.md
        - "MCID Spam Tags": setup/mcid.md
    - Using CallTelemetry:
      - "Policies": features/policy.md
      - "MCID Blocking": features/mcid.md
      - "Whare are Apps?": features/apps.md
      - "Organizations": features/organizations.md
    - App Catalog:
        - "Catalog": apps/webhooks.md
        # - "SMTP": apps/smtp.md
    - Troubleshooting:
      - "Logs": troubleshooting/logs.md
      - "CDR": troubleshooting/cdr.md
      # - "CURRI/ECC": troubleshooting/curri.md
extra_css: [extra.css]
theme: 
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
google_analytics: ['UA-153385083-2', 'mkdocs.org']
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
copyright: Copyright &copy; 2021 CallTelemetry
