apiVersion: 1

datasources:
  - name: CallTelemetry Prometheus
    uid: calltelemetry-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET

  - name: CallTelemetry AlertManager
    uid: calltelemetry-alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false

  - name: CallTelemetry Tempo
    uid: calltelemetry-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: calltelemetry-prometheus
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: ''
      lokiSearch:
        datasourceUid: ''
