apiVersion: 1

datasources:
  - name: CallTelemetry Prometheus
    uid: calltelemetry-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET

  - name: CallTelemetry AlertManager
    uid: calltelemetry-alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
