version: "3"
services:
  db:
    image: "bitnami/postgresql"
    restart: "always"
    environment:
      - POSTGRES_USER=calltelemetry
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calltelemetry_prod
    expose: [5432]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    image: "calltelemetry/web:0.4.0"
    restart: "always"
    ports: ["80:4000", "22:3022"]
    environment:
      - DB_USER=calltelemetry
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=db
      - DB_NAME=calltelemetry_prod
      - INTERNAL_PORT=4000
      - EXTERNAL_PORT=80
      - HOSTNAME=$DEFAULT_IPV4
      - EXTERNAL_IP=$DEFAULT_IPV4
      - SECRET_KEY_BASE=wu3JgPq0IMvIMsJJZ940biL7jVkhLvHJ9I6aqlvhgonVA2eMdOgmdEjWMFAjRKSr
      - SIGNING_SALT=7HekGYwxATz33gM/rH9q2mV+uKJq5/H
    volumes:
      - ./sftp:/sftp