#!/usr/bin/env bash
# k3s-firstboot.sh — Interactive first-boot setup wizard for K3s appliance
# Prompts for MetalLB IPs, credentials, TLS mode, then applies via helmfile.
set -euo pipefail

K8S_DIR="/opt/calltelemetry/k8s"
RUNTIME_VALUES="${K8S_DIR}/env-appliance-runtime.yaml"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        Call Telemetry — K3s Appliance First-Boot Setup      ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  This wizard configures your appliance for first use.       ║"
echo "║  It will prompt for network, credentials, and TLS settings. ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ─── Step 1: Confirm K8s deployment mode ───────────────────────────────────

echo "Deployment mode: Kubernetes (K3s)"
echo "This appliance runs on K3s with Helm-managed services."
echo ""

# ─── Step 2: Network / MetalLB IPs ────────────────────────────────────────

# Auto-detect host IP
DETECTED_IP=""
if [ -f /etc/network-environment ]; then
  source /etc/network-environment
  DETECTED_IP="${DEFAULT_IPV4:-}"
fi

if [ -z "${DETECTED_IP}" ]; then
  DETECTED_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
fi

echo "─── Network Configuration ───"
echo ""
if [ -n "${DETECTED_IP}" ]; then
  echo "  Detected IP: ${DETECTED_IP}"
fi
echo ""

read -rp "  Load Balancer IP for web management [${DETECTED_IP}]: " ADMIN_IP < /dev/tty
ADMIN_IP="${ADMIN_IP:-${DETECTED_IP}}"

read -rp "  Primary CURRI API IP [${ADMIN_IP}]: " PRIMARY_IP < /dev/tty
PRIMARY_IP="${PRIMARY_IP:-${ADMIN_IP}}"

read -rp "  Secondary CURRI API IP [${PRIMARY_IP}]: " SECONDARY_IP < /dev/tty
SECONDARY_IP="${SECONDARY_IP:-${PRIMARY_IP}}"

read -rp "  Hostname [calltelemetry.local]: " CT_HOSTNAME < /dev/tty
CT_HOSTNAME="${CT_HOSTNAME:-calltelemetry.local}"

echo ""
echo "  Network summary:"
echo "    Admin/Web IP:     ${ADMIN_IP}"
echo "    Primary CURRI:    ${PRIMARY_IP}"
echo "    Secondary CURRI:  ${SECONDARY_IP}"
echo "    Hostname:         ${CT_HOSTNAME}"
echo ""

# ─── Step 3: Credentials ──────────────────────────────────────────────────

echo "─── Credentials ───"
echo ""
echo "  1) Default credentials (documented defaults, change later)"
echo "  2) Custom credentials (set now)"
echo ""
read -rp "  Choose [1]: " CRED_CHOICE < /dev/tty
CRED_CHOICE="${CRED_CHOICE:-1}"

PG_PASSWORD="$(openssl rand -base64 16 2>/dev/null | tr -d '/+=' | head -c 16)"
NATS_TOKEN=""

if [ "${CRED_CHOICE}" = "2" ]; then
  echo ""
  # Generate a random default
  RANDOM_PW=$(openssl rand -base64 16 2>/dev/null | tr -d '/+=' | head -c 16)
  read -rp "  PostgreSQL password [auto: ${RANDOM_PW}]: " PG_PASSWORD < /dev/tty
  PG_PASSWORD="${PG_PASSWORD:-${RANDOM_PW}}"

  RANDOM_TOKEN=$(openssl rand -hex 16 2>/dev/null)
  read -rp "  NATS auth token [auto: ${RANDOM_TOKEN}]: " NATS_TOKEN < /dev/tty
  NATS_TOKEN="${NATS_TOKEN:-${RANDOM_TOKEN}}"
fi

echo ""

# ─── Step 4: TLS Mode ─────────────────────────────────────────────────────

echo "─── TLS Configuration ───"
echo ""
echo "  1) Self-signed certificate (default, immediate)"
echo "  2) Let's Encrypt (requires public DNS + port 80 access)"
echo ""
read -rp "  Choose [1]: " TLS_CHOICE < /dev/tty
TLS_CHOICE="${TLS_CHOICE:-1}"

LE_EMAIL=""
LE_DOMAIN=""
CERT_ISSUER="selfsigned"

if [ "${TLS_CHOICE}" = "2" ]; then
  read -rp "  Let's Encrypt email: " LE_EMAIL < /dev/tty
  read -rp "  Public domain name: " LE_DOMAIN < /dev/tty
  CT_HOSTNAME="${LE_DOMAIN}"
  CERT_ISSUER="letsencrypt-prod"
fi

echo ""

# ─── Write runtime values ─────────────────────────────────────────────────

echo "Writing runtime configuration..."
cat > "${RUNTIME_VALUES}" <<YAML
# Auto-generated by k3s-firstboot.sh — do not edit manually
# Re-run /opt/calltelemetry/k3s-firstboot.sh to reconfigure

# Environment overrides
env:
  domain: "${CT_HOSTNAME}"

# MetalLB IP addresses
metallb:
  primary_ip: "${PRIMARY_IP}"
  secondary_ip: "${SECONDARY_IP}"
  admin_ip: "${ADMIN_IP}"

# Ingress IP overrides (must match MetalLB)
ingress:
  primary_api:
    metal_ip_address: "${PRIMARY_IP}"
  secondary_api:
    metal_ip_address: "${SECONDARY_IP}"
  admin_api:
    metal_ip_address: "${ADMIN_IP}"

# API hostname
api:
  hostname: "${CT_HOSTNAME}"

# Vue Web hostname
vue_web:
  hostname: "${CT_HOSTNAME}"

# Credentials
credentials:
  postgres_password: "${PG_PASSWORD}"
  nats_token: "${NATS_TOKEN}"

# TLS
tls:
  issuer: "${CERT_ISSUER}"
  email: "${LE_EMAIL}"
YAML

echo "  Saved to: ${RUNTIME_VALUES}"

# ─── Set hostname ──────────────────────────────────────────────────────────

sudo hostnamectl set-hostname "${CT_HOSTNAME}" 2>/dev/null || true

# ─── Start K3s ─────────────────────────────────────────────────────────────

echo ""
echo "Starting K3s..."
sudo systemctl start k3s

echo "Waiting for K3s node to be Ready..."
for i in $(seq 1 60); do
  if kubectl get nodes 2>/dev/null | grep -q " Ready"; then
    echo "  K3s node is Ready."
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "  WARNING: K3s node not Ready after 5 minutes. Continuing anyway..."
  fi
  sleep 5
done

# ─── Apply via Helmfile ────────────────────────────────────────────────────

echo ""
echo "Applying configuration via helmfile..."
cd "${K8S_DIR}"

# Helmfile sync with runtime values overlay
helmfile --environment ct-appliance \
  --state-values-file "${RUNTIME_VALUES}" \
  sync

echo ""
echo "Waiting for pods to start..."
sleep 15

# Wait for all pods in ct namespace to be Ready (up to 5 minutes)
echo "Checking pod status..."
for i in $(seq 1 60); do
  NOT_READY=$(kubectl get pods -n ct --no-headers 2>/dev/null | grep -v "Running\|Completed" | wc -l || echo "99")
  if [ "${NOT_READY}" -eq 0 ]; then
    echo "  All pods are Running!"
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "  WARNING: Some pods are not ready after 5 minutes."
    kubectl get pods -n ct --no-headers 2>/dev/null | grep -v "Running\|Completed" || true
  fi
  sleep 5
done

echo ""
kubectl get pods -n ct -o wide 2>/dev/null || true

# ─── Verify health ────────────────────────────────────────────────────────

echo ""
echo "Checking API health..."
for i in $(seq 1 12); do
  if curl -ksSf "https://${ADMIN_IP}/api/health" >/dev/null 2>&1; then
    echo "  API is healthy!"
    break
  fi
  if curl -ksSf "http://${ADMIN_IP}/api/health" >/dev/null 2>&1; then
    echo "  API is healthy (HTTP)!"
    break
  fi
  if [ "$i" -eq 12 ]; then
    echo "  WARNING: API health check not responding yet. It may still be initializing."
    echo "  Check: kubectl get pods -n ct"
  fi
  sleep 10
done

# ─── Mark as configured ───────────────────────────────────────────────────

sudo touch /etc/ct-k3s-configured
echo "k8s" | sudo tee /etc/ct-deploy-mode > /dev/null

# ─── Done ──────────────────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           K3s Appliance Setup Complete!                     ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                            ║"
echo "║  Web UI:    https://${ADMIN_IP}$(printf '%*s' $((38 - ${#ADMIN_IP})) '')║"
echo "║  Hostname:  ${CT_HOSTNAME}$(printf '%*s' $((44 - ${#CT_HOSTNAME})) '')║"
echo "║  SSH:       port 2222                                      ║"
echo "║                                                            ║"
echo "║  Commands:                                                 ║"
echo "║    kubectl get pods -n ct    — Check services              ║"
echo "║    k9s -n ct                 — Kubernetes TUI              ║"
echo "║    ct shell                  — Appliance management        ║"
echo "║    ct status                 — Service status              ║"
echo "║                                                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
