name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose (Default)
        run: |
          docker compose config

      - name: Validate Docker Compose (with .env.example & profiles)
        run: |
          cp .env.example .env
          docker compose config
          docker compose --profile jtapi config
          docker compose --profile storage config
